"use client";

// Print-ready invoice / receipt.
//
// Layout: org logo + name on the left, invoice number on the right;
// patient block; line items; tax breakdown (CGST/SGST/IGST for IN
// intra-state, IGST for inter-state, VAT/sales for the rest);
// payments + balance; org-supplied footer; "Generated by OduDoc"
// co-brand below.
//
// Watermark + audit log mirror the document-viewer surface — same
// diagonal patient ID + IP overlay, same beforeprint hook fires
// the audit event.

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";

interface RenderResp {
  render: {
    invoice: {
      id: string; invoiceNumber: string; status: string;
      patientId: string; encounterId?: string;
      issuedAt?: string; dueAt?: string; notes?: string;
      items: Array<{ id: string; description: string; quantity: number; unitPrice: number; discount?: number; category?: string }>;
      payments: Array<{ amount: number; method: string; reference?: string; receivedAt: string }>;
      paidTotal: number; balance: number;
    };
    org: { id: string; name: string; country: string } | null;
    branding: {
      logoLight?: string; primaryColor?: string;
      displayName?: string; invoiceFooter?: string; websiteUrl?: string;
    } | null;
    tax: {
      regime: string;
      lines: Array<{ description: string; category: string; amountRupees: number; appliedRatePct: number; taxRupees: number; bucketLabel: string }>;
      exemptSubtotal: number;
      taxableStandardSubtotal: number;
      taxableReducedSubtotal: number;
      cgstRupees?: number; sgstRupees?: number; igstRupees?: number;
      vatRupees?: number; salesTaxRupees?: number;
      totalTaxRupees: number; grandTotalRupees: number;
    };
    displayName: string;
    currency: string;
    primaryColor: string;
  };
  watermark: { patientUserId: string; ip?: string; viewedAt: string };
}

function fmtMoney(n: number, currency: string): string {
  return `${currency === "INR" ? "₹" : currency + " "}${Math.round(n).toLocaleString()}`;
}

export default function InvoicePrintPage() {
  const params = useParams<{ id: string; orgId: string }>();
  const id = params?.id;
  const orgId = params?.orgId;
  const [data, setData] = useState<RenderResp | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id || !orgId) return;
    fetch(`/api/invoices/render?id=${encodeURIComponent(id)}&orgId=${encodeURIComponent(orgId)}`, { cache: "no-store" })
      .then((r) => r.ok ? r.json() : Promise.reject(r.statusText))
      .then((d) => setData(d))
      .catch((e) => setError(typeof e === "string" ? e : "Failed to load"));
  }, [id, orgId]);

  // Beforeprint → audit (mirrors documents). The render endpoint
  // already logged the view; this captures the print intent so
  // /dashboard/audit shows both rows.
  useEffect(() => {
    const onPrint = () => {
      // Best-effort POST to audit. We don't block the print dialog
      // on the response.
      fetch("/api/audit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({}) }).catch(() => {});
    };
    window.addEventListener("beforeprint", onPrint);
    return () => window.removeEventListener("beforeprint", onPrint);
  }, []);

  if (error) return <p className="mx-auto mt-12 max-w-md rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</p>;
  if (!data) return <p className="mx-auto mt-12 max-w-md rounded-xl bg-white p-8 text-center text-sm text-slate-400 shadow-sm">Loading…</p>;

  const { render, watermark } = data;
  const { invoice, branding, tax } = render;
  const intraGst = tax.cgstRupees !== undefined && tax.sgstRupees !== undefined;
  const interGst = tax.igstRupees !== undefined;

  return (
    <div className="min-h-screen bg-slate-100 print:bg-white">
      {/* Action bar — hidden on print */}
      <div className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur-md print:hidden">
        <div className="mx-auto flex max-w-4xl items-center justify-between gap-3 px-4 py-3">
          <Link href="/dashboard" className="text-sm font-semibold text-slate-700 hover:text-indigo-700">← Back</Link>
          <div className="flex items-center gap-2">
            <span className="rounded-full bg-rose-50 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-rose-700 ring-1 ring-rose-200">
              View-only · download disabled
            </span>
            <button onClick={() => window.print()} className="rounded-lg px-4 py-2 text-sm font-bold text-white shadow-sm" style={{ background: render.primaryColor }}>
              Print
            </button>
          </div>
        </div>
        <p className="mx-auto max-w-4xl px-4 pb-2 text-[10px] text-slate-500">
          Tax recomputed against {render.org?.country || "country"} rules. Every view + print is logged on
          {" "}<Link href="/dashboard/audit" className="font-semibold text-indigo-600 hover:underline">Audit log</Link>.
        </p>
      </div>

      <div className="mx-auto max-w-4xl px-4 py-6 print:max-w-none print:p-0">
        <div className="relative overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 print:shadow-none print:ring-0">
          {/* Brand stripe + header */}
          <div className="border-b border-slate-200 px-8 py-6" style={{ borderTopColor: render.primaryColor, borderTopWidth: 6 }}>
            <div className="flex items-start justify-between gap-4">
              <div className="flex items-center gap-4">
                {branding?.logoLight ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={branding.logoLight} alt="" className="h-14 w-auto object-contain" />
                ) : (
                  <div className="flex h-14 w-14 items-center justify-center rounded-xl text-base font-extrabold text-white" style={{ background: render.primaryColor }}>
                    {render.displayName.slice(0, 2).toUpperCase()}
                  </div>
                )}
                <div>
                  <p className="text-lg font-extrabold text-slate-900">{render.displayName}</p>
                  {branding?.websiteUrl && <p className="text-xs text-slate-500">{branding.websiteUrl}</p>}
                  <p className="text-xs text-slate-500">{render.org?.country}</p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-[10px] uppercase tracking-widest text-slate-500">Tax invoice</p>
                <p className="mt-0.5 font-mono text-sm font-bold text-slate-900">{invoice.invoiceNumber}</p>
                <p className="mt-1 text-[10px] uppercase tracking-wider" style={{ color: render.primaryColor }}>{invoice.status}</p>
              </div>
            </div>
          </div>

          {/* Patient + dates */}
          <div className="grid grid-cols-2 border-b border-slate-100 px-8 py-4 text-xs">
            <div>
              <p className="text-[10px] uppercase tracking-wider text-slate-500">Bill to</p>
              <p className="mt-1 font-bold text-slate-900">Patient ID {invoice.patientId}</p>
              {invoice.encounterId && <p className="text-slate-500">Encounter {invoice.encounterId}</p>}
            </div>
            <div className="text-right">
              {invoice.issuedAt && <p className="text-slate-500">Issued <b className="text-slate-900">{new Date(invoice.issuedAt).toLocaleDateString()}</b></p>}
              {invoice.dueAt && <p className="text-slate-500">Due <b className="text-slate-900">{new Date(invoice.dueAt).toLocaleDateString()}</b></p>}
            </div>
          </div>

          {/* Line items + tax */}
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50 text-[10px] uppercase tracking-wider text-slate-600">
                <th className="px-8 py-2 text-left">Description</th>
                <th className="px-3 py-2 text-right">Qty</th>
                <th className="px-3 py-2 text-right">Unit</th>
                <th className="px-3 py-2 text-right">Tax</th>
                <th className="px-8 py-2 text-right">Amount</th>
              </tr>
            </thead>
            <tbody>
              {invoice.items.map((it, i) => {
                const lineSubtotal = it.quantity * it.unitPrice - (it.discount || 0);
                const tx = tax.lines[i];
                return (
                  <tr key={it.id} className="border-b border-slate-100">
                    <td className="px-8 py-3">
                      <p className="font-semibold text-slate-900">{it.description}</p>
                      <p className="text-[10px] uppercase tracking-wider text-slate-400">{it.category} · {tx?.bucketLabel || "—"}</p>
                    </td>
                    <td className="px-3 py-3 text-right tabular-nums text-slate-700">{it.quantity}</td>
                    <td className="px-3 py-3 text-right tabular-nums text-slate-700">{fmtMoney(it.unitPrice, render.currency)}</td>
                    <td className="px-3 py-3 text-right text-[10px] tabular-nums text-slate-500">{tx?.appliedRatePct ?? 0}%</td>
                    <td className="px-8 py-3 text-right tabular-nums font-semibold text-slate-900">{fmtMoney(lineSubtotal, render.currency)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>

          {/* Totals */}
          <div className="border-t border-slate-200 px-8 py-4 text-sm">
            <div className="ml-auto max-w-sm space-y-1.5">
              <Row label="Exempt subtotal" value={fmtMoney(tax.exemptSubtotal, render.currency)} />
              <Row label="Standard-rate subtotal" value={fmtMoney(tax.taxableStandardSubtotal, render.currency)} />
              {tax.taxableReducedSubtotal > 0 && (
                <Row label="Reduced-rate subtotal" value={fmtMoney(tax.taxableReducedSubtotal, render.currency)} />
              )}
              {intraGst && (
                <>
                  <Row label="CGST" value={fmtMoney(tax.cgstRupees!, render.currency)} muted />
                  <Row label="SGST" value={fmtMoney(tax.sgstRupees!, render.currency)} muted />
                </>
              )}
              {interGst && <Row label="IGST" value={fmtMoney(tax.igstRupees!, render.currency)} muted />}
              {tax.vatRupees !== undefined && tax.vatRupees > 0 && <Row label="VAT" value={fmtMoney(tax.vatRupees, render.currency)} muted />}
              {tax.salesTaxRupees !== undefined && tax.salesTaxRupees > 0 && <Row label="Sales tax" value={fmtMoney(tax.salesTaxRupees, render.currency)} muted />}
              <div className="border-t border-slate-200 pt-2 mt-2">
                <Row label="Grand total" value={fmtMoney(tax.grandTotalRupees, render.currency)} bold colorHex={render.primaryColor} />
              </div>
              {invoice.paidTotal > 0 && (
                <Row label="Paid" value={`− ${fmtMoney(invoice.paidTotal, render.currency)}`} muted />
              )}
              <Row label="Balance" value={fmtMoney(invoice.balance, render.currency)} bold />
            </div>
          </div>

          {/* Payments log */}
          {invoice.payments.length > 0 && (
            <div className="border-t border-slate-100 px-8 py-4 text-xs">
              <p className="text-[10px] uppercase tracking-wider text-slate-500">Payments</p>
              <ul className="mt-2 space-y-1">
                {invoice.payments.map((p, i) => (
                  <li key={i} className="flex justify-between text-slate-600">
                    <span>
                      {new Date(p.receivedAt).toLocaleDateString()} · {p.method.toUpperCase()}
                      {p.reference && <span className="ml-2 text-slate-400">{p.reference}</span>}
                    </span>
                    <span className="tabular-nums font-semibold text-slate-900">{fmtMoney(p.amount, render.currency)}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {invoice.notes && (
            <div className="border-t border-slate-100 px-8 py-3 text-xs italic text-slate-500">{invoice.notes}</div>
          )}

          {/* Footer */}
          <div className="border-t border-slate-200 bg-slate-50 px-8 py-3 text-[10px] text-slate-500">
            {branding?.invoiceFooter || `${render.displayName} · ${render.org?.country || ""}`}
            <span className="ml-2 text-slate-400">· Generated by OduDoc</span>
          </div>

          {/* Watermark — mirrors the document viewer */}
          <div
            className="pointer-events-none absolute inset-0 select-none print:opacity-30"
            style={{ backgroundImage: `repeating-linear-gradient(-30deg, rgba(99,102,241,0.10) 0, rgba(99,102,241,0.10) 1px, transparent 1px, transparent 240px)` }}
          >
            {Array.from({ length: 14 }).map((_, row) => (
              <div key={row} className="absolute inset-x-0 -rotate-12" style={{ top: `${row * 14}%` }}>
                <div className="flex justify-around whitespace-nowrap text-[10px] font-bold uppercase tracking-[0.3em] text-indigo-600/30">
                  {Array.from({ length: 4 }).map((__, col) => (
                    <span key={col}>OduDoc · {watermark.patientUserId} · {watermark.ip || "no-ip"} · {new Date(watermark.viewedAt).toLocaleString()}</span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Print-only audit footer */}
        <div className="hidden print:block">
          <p className="mt-4 px-4 text-[10px] text-slate-500">
            Printed from OduDoc · Patient ID {watermark.patientUserId} · IP {watermark.ip || "unknown"} · {new Date(watermark.viewedAt).toLocaleString()}.
          </p>
        </div>
      </div>

      <style jsx global>{`
        @media print {
          @page { margin: 12mm; }
          body { background: white; }
        }
      `}</style>
    </div>
  );
}

function Row({ label, value, bold, muted, colorHex }: { label: string; value: string; bold?: boolean; muted?: boolean; colorHex?: string }) {
  return (
    <div className="flex items-baseline justify-between gap-4">
      <span className={`text-xs ${muted ? "text-slate-500" : "text-slate-700"} ${bold ? "font-bold" : ""}`}>{label}</span>
      <span
        className={`tabular-nums ${bold ? "text-base font-extrabold" : "text-sm font-semibold"}`}
        style={colorHex && bold ? { color: colorHex } : undefined}
      >
        {value}
      </span>
    </div>
  );
}
