// Preset clinical vocabulary for the AI Prescription form.
//
// These are curated lists a doctor can click through instead of typing
// everything by hand. Chosen to cover >90% of outpatient primary-care
// use cases. The doctor can still free-type anything — the picker just
// appends to the existing comma-separated value.

export const SEX_OPTIONS = [
  "Male",
  "Female",
  "Other",
  "Intersex",
  "Non-binary",
  "Transgender (M→F)",
  "Transgender (F→M)",
  "Prefer not to say",
];

export const DURATION_OPTIONS = [
  "A few hours",
  "Since last night",
  "1 day",
  "2 days",
  "3 days",
  "4–5 days",
  "1 week",
  "2 weeks",
  "3 weeks",
  "1 month",
  "2 months",
  "3 months",
  "6 months",
  "> 1 year",
  "Chronic / recurrent",
  "Since birth",
];

export const COMMON_SYMPTOMS = [
  // General / constitutional
  "Fever",
  "Low-grade fever",
  "High-grade fever",
  "Chills / rigors",
  "Night sweats",
  "Fatigue",
  "Weight loss",
  "Weight gain",
  "Loss of appetite",
  "Dehydration",
  "Weakness",
  "Malaise",
  // Head & ENT
  "Headache",
  "Migraine",
  "Dizziness / vertigo",
  "Sore throat",
  "Runny nose",
  "Nasal congestion",
  "Sneezing",
  "Ear pain",
  "Ear discharge",
  "Hearing loss",
  "Tinnitus",
  "Toothache",
  "Mouth ulcers",
  // Eye
  "Red eye",
  "Eye pain",
  "Blurred vision",
  "Double vision",
  "Photophobia",
  "Watery eyes",
  // Respiratory
  "Dry cough",
  "Productive cough",
  "Cough with blood",
  "Shortness of breath",
  "Wheezing",
  "Chest tightness",
  "Chest pain",
  // Cardiovascular
  "Palpitations",
  "Swollen ankles",
  "Fainting / syncope",
  "Orthopnea",
  // GI
  "Nausea",
  "Vomiting",
  "Vomiting with blood",
  "Abdominal pain",
  "Epigastric pain",
  "Right upper quadrant pain",
  "Lower abdominal pain",
  "Bloating",
  "Heartburn / reflux",
  "Diarrhea",
  "Bloody stools",
  "Black / tarry stools",
  "Constipation",
  "Jaundice",
  // GU / Renal
  "Burning urination",
  "Frequent urination",
  "Blood in urine",
  "Inability to pass urine",
  "Flank pain",
  "Genital discharge",
  "Irregular periods",
  "Heavy periods",
  "Missed period",
  "Pelvic pain",
  // Musculoskeletal
  "Joint pain",
  "Joint swelling",
  "Back pain",
  "Neck pain",
  "Muscle pain",
  "Stiffness",
  "Limb weakness",
  // Neuro
  "Confusion",
  "Memory loss",
  "Seizure",
  "Slurred speech",
  "Numbness / tingling",
  "Loss of consciousness",
  "Tremor",
  // Skin
  "Rash",
  "Itching",
  "Hives",
  "Skin peeling",
  "Wound not healing",
  "Swelling",
  "Bruising",
  // Psych
  "Anxiety",
  "Low mood",
  "Insomnia",
  "Panic attacks",
  "Poor concentration",
];

export const COMMON_HISTORY = [
  "Diabetes mellitus type 2",
  "Diabetes mellitus type 1",
  "Hypertension",
  "Hyperlipidemia",
  "Coronary artery disease",
  "Prior myocardial infarction",
  "Heart failure",
  "Atrial fibrillation",
  "Stroke / TIA",
  "Asthma",
  "COPD",
  "Tuberculosis (past)",
  "Chronic kidney disease",
  "Liver disease / cirrhosis",
  "Hepatitis B",
  "Hepatitis C",
  "HIV",
  "Hypothyroidism",
  "Hyperthyroidism",
  "PCOS",
  "Anemia",
  "Cancer (specify)",
  "Epilepsy / seizure disorder",
  "Migraine",
  "Depression",
  "Anxiety disorder",
  "Bipolar disorder",
  "GERD",
  "Peptic ulcer disease",
  "IBS",
  "IBD / Crohn’s / UC",
  "Gallstones",
  "Rheumatoid arthritis",
  "Osteoarthritis",
  "Osteoporosis",
  "Gout",
  "Psoriasis",
  "Eczema",
  "Allergic rhinitis",
  "Pregnancy (current)",
  "Breastfeeding",
  "Prior cesarean section",
  "Prior appendectomy",
  "Prior cholecystectomy",
  "Smoker",
  "Former smoker",
  "Alcohol use",
  "Recreational drug use",
];

export const COMMON_ALLERGIES = [
  "No known drug allergy",
  "Penicillin",
  "Amoxicillin",
  "Cephalosporins",
  "Sulfa drugs",
  "Aspirin",
  "NSAIDs",
  "Ibuprofen",
  "Paracetamol",
  "Codeine / opioids",
  "Local anesthetics",
  "Contrast media (iodinated)",
  "Latex",
  "Peanuts",
  "Tree nuts",
  "Shellfish",
  "Eggs",
  "Milk / dairy",
  "Soy",
  "Wheat / gluten",
  "Dust mites",
  "Pollen",
  "Pet dander",
  "Bee / wasp sting",
];

export const COMMON_MEDICATIONS = [
  "Metformin 500 mg BD",
  "Metformin 1 g BD",
  "Glimepiride 2 mg OD",
  "Insulin (basal)",
  "Insulin (basal-bolus)",
  "Amlodipine 5 mg OD",
  "Amlodipine 10 mg OD",
  "Telmisartan 40 mg OD",
  "Losartan 50 mg OD",
  "Ramipril 5 mg OD",
  "Atenolol 50 mg OD",
  "Metoprolol 25 mg BD",
  "Atorvastatin 10 mg OD",
  "Atorvastatin 20 mg OD",
  "Rosuvastatin 10 mg OD",
  "Aspirin 75 mg OD",
  "Clopidogrel 75 mg OD",
  "Warfarin",
  "Apixaban 5 mg BD",
  "Levothyroxine 50 mcg OD",
  "Levothyroxine 100 mcg OD",
  "Omeprazole 20 mg OD",
  "Pantoprazole 40 mg OD",
  "Ranitidine 150 mg BD",
  "Salbutamol inhaler PRN",
  "Budesonide/formoterol inhaler",
  "Montelukast 10 mg OD",
  "Cetirizine 10 mg OD",
  "Prednisolone (taper)",
  "Paracetamol 500 mg QID PRN",
  "Ibuprofen 400 mg TDS PRN",
  "Tramadol 50 mg PRN",
  "Sertraline 50 mg OD",
  "Escitalopram 10 mg OD",
  "Fluoxetine 20 mg OD",
  "Alprazolam 0.25 mg HS",
  "Gabapentin 300 mg TDS",
  "Pregabalin 75 mg BD",
  "Oral contraceptive pill",
  "Iron + folic acid OD",
  "Vitamin D 60,000 IU weekly",
  "Calcium 500 mg BD",
];

export const VITALS_TEMPLATES = [
  "BP 120/80, HR 72, Temp 37°C, SpO2 98%, RR 16",
  "BP 130/85, HR 88, Temp 38.2°C, SpO2 97%, RR 20",
  "BP 140/90, HR 92, Temp 37.1°C, SpO2 96%",
  "BP 150/100, HR 100, Temp 37°C, SpO2 95%",
  "BP 160/110, HR 110, Temp 38°C, SpO2 94%, RR 24",
  "BP 90/60, HR 110, Temp 38.5°C, SpO2 93%, RR 26",
  "BP 80/50, HR 130, Temp 39°C, SpO2 90%, RR 30",
  "BP 120/80, HR 72, afebrile, SpO2 99%, RBS 110",
  "BP 130/80, HR 80, RBS 280 mg/dL, urine ketones +",
];
