// Curated suggestion lists powering autocomplete (datalists) and quick-add
// chips inside the doctor prescription form. These are intentionally generic
// and not exhaustive — they're meant to speed up the most common entries.
// Doctors can always type anything; the lists only guide, never restrict.

export const COMMON_SYMPTOMS = [
  "Fever",
  "High-grade fever",
  "Low-grade fever",
  "Chills",
  "Sweating",
  "Night sweats",
  "Cough",
  "Dry cough",
  "Productive cough",
  "Cough with blood",
  "Sore throat",
  "Hoarseness",
  "Runny nose",
  "Nasal congestion",
  "Sneezing",
  "Post-nasal drip",
  "Headache",
  "Migraine",
  "Body ache",
  "Muscle pain",
  "Fatigue",
  "Weakness",
  "Malaise",
  "Nausea",
  "Vomiting",
  "Diarrhea",
  "Loose stools",
  "Constipation",
  "Abdominal pain",
  "Abdominal bloating",
  "Heartburn",
  "Acid reflux",
  "Loss of appetite",
  "Weight loss",
  "Weight gain",
  "Chest pain",
  "Palpitations",
  "Shortness of breath",
  "Wheezing",
  "Dizziness",
  "Vertigo",
  "Fainting",
  "Back pain",
  "Neck pain",
  "Joint pain",
  "Joint swelling",
  "Muscle cramps",
  "Rash",
  "Itching",
  "Hives",
  "Swelling",
  "Dry skin",
  "Acne",
  "Burning urination",
  "Frequent urination",
  "Blood in urine",
  "Difficulty urinating",
  "Ear pain",
  "Ear discharge",
  "Hearing loss",
  "Ringing in ears",
  "Eye redness",
  "Eye discharge",
  "Blurred vision",
  "Watery eyes",
  "Insomnia",
  "Excessive sleep",
  "Anxiety",
  "Depression",
  "Mood swings",
  "Memory problems",
  "Numbness",
  "Tingling sensation",
  "Tremors",
  "Irregular periods",
  "Heavy menstrual bleeding",
  "Painful periods",
  "Vaginal discharge",
  "Erectile dysfunction",
  "Hair loss",
  "Swollen lymph nodes",
];

export const COMMON_DIAGNOSES = [
  "Upper respiratory tract infection",
  "Lower respiratory tract infection",
  "Acute pharyngitis",
  "Viral fever",
  "Dengue fever",
  "Typhoid fever",
  "Malaria",
  "Chikungunya",
  "COVID-19",
  "Influenza",
  "Acute bronchitis",
  "Chronic bronchitis",
  "Pneumonia",
  "Acute sinusitis",
  "Chronic sinusitis",
  "Allergic rhinitis",
  "Acute tonsillitis",
  "Laryngitis",
  "Acute gastroenteritis",
  "Gastritis",
  "GERD (Acid reflux)",
  "Peptic ulcer disease",
  "Irritable bowel syndrome",
  "Constipation",
  "Hemorrhoids",
  "Food poisoning",
  "Viral hepatitis",
  "Urinary tract infection",
  "Kidney stones",
  "Prostatitis",
  "Hypertension",
  "Stage 1 hypertension",
  "Type 2 diabetes mellitus",
  "Pre-diabetes",
  "Hyperlipidemia",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Obesity",
  "Vitamin D deficiency",
  "Vitamin B12 deficiency",
  "Iron deficiency anaemia",
  "Anaemia",
  "Migraine",
  "Tension headache",
  "Cluster headache",
  "Vertigo (BPPV)",
  "Insomnia",
  "Anxiety disorder",
  "Depression",
  "Acute otitis media",
  "Otitis externa",
  "Conjunctivitis",
  "Stye",
  "Dermatitis",
  "Atopic dermatitis (Eczema)",
  "Contact dermatitis",
  "Psoriasis",
  "Acne vulgaris",
  "Urticaria (Hives)",
  "Fungal skin infection",
  "Scabies",
  "Cellulitis",
  "Asthma",
  "Asthma exacerbation",
  "COPD",
  "Allergic cough",
  "Lower back pain",
  "Cervical spondylosis",
  "Lumbar spondylosis",
  "Sciatica",
  "Osteoarthritis",
  "Rheumatoid arthritis",
  "Gout",
  "Musculoskeletal strain",
  "Sprain",
  "Menstrual irregularity",
  "Dysmenorrhea",
  "PCOS",
  "Vaginal candidiasis",
  "Bacterial vaginosis",
  "Erectile dysfunction",
  "Benign prostatic hyperplasia",
  "Dental caries",
];

// Common medicines used across general practice. Format includes strength
// so the doctor can pick a prefilled entry and tweak as needed.
export const COMMON_MEDICINES = [
  // Analgesics / Antipyretics
  "Paracetamol 500mg",
  "Paracetamol 650mg",
  "Paracetamol syrup 250mg/5ml",
  "Ibuprofen 200mg",
  "Ibuprofen 400mg",
  "Ibuprofen 600mg",
  "Diclofenac 50mg",
  "Naproxen 500mg",
  "Aceclofenac 100mg",
  "Aspirin 75mg",
  "Aspirin 325mg",
  "Tramadol 50mg",
  // Antibiotics
  "Amoxicillin 500mg",
  "Amoxicillin + Clavulanic Acid 625mg",
  "Amoxicillin + Clavulanic Acid 1g",
  "Azithromycin 250mg",
  "Azithromycin 500mg",
  "Cefixime 200mg",
  "Cefuroxime 500mg",
  "Cephalexin 500mg",
  "Ciprofloxacin 500mg",
  "Levofloxacin 500mg",
  "Ofloxacin 200mg",
  "Doxycycline 100mg",
  "Clarithromycin 500mg",
  "Metronidazole 400mg",
  "Tinidazole 500mg",
  "Nitrofurantoin 100mg",
  "Trimethoprim + Sulfamethoxazole 960mg",
  // Antifungals / Antivirals
  "Fluconazole 150mg",
  "Itraconazole 100mg",
  "Terbinafine 250mg",
  "Acyclovir 400mg",
  "Oseltamivir 75mg",
  // GI / Acid suppression
  "Omeprazole 20mg",
  "Pantoprazole 40mg",
  "Esomeprazole 40mg",
  "Rabeprazole 20mg",
  "Ranitidine 150mg",
  "Famotidine 20mg",
  "Sucralfate 1g",
  "Antacid syrup 10ml",
  // Antiemetics
  "Ondansetron 4mg",
  "Ondansetron 8mg",
  "Domperidone 10mg",
  "Metoclopramide 10mg",
  // Antihistamines
  "Loratadine 10mg",
  "Cetirizine 10mg",
  "Levocetirizine 5mg",
  "Fexofenadine 120mg",
  "Fexofenadine 180mg",
  "Chlorpheniramine 4mg",
  "Hydroxyzine 25mg",
  // Respiratory
  "Montelukast 10mg",
  "Montelukast + Levocetirizine",
  "Salbutamol inhaler 100mcg",
  "Budesonide inhaler 200mcg",
  "Salbutamol + Ipratropium nebulizer",
  "Formoterol + Budesonide inhaler",
  "Ambroxol syrup 30mg/5ml",
  "Bromhexine 8mg",
  "Dextromethorphan syrup",
  // Steroids
  "Prednisolone 5mg",
  "Prednisolone 10mg",
  "Dexamethasone 4mg",
  "Hydrocortisone cream 1%",
  // Diabetes
  "Metformin 500mg",
  "Metformin 1000mg",
  "Glimepiride 1mg",
  "Glimepiride 2mg",
  "Sitagliptin 50mg",
  "Teneligliptin 20mg",
  "Insulin glargine",
  "Insulin regular",
  // Cardiovascular
  "Amlodipine 5mg",
  "Amlodipine 10mg",
  "Telmisartan 40mg",
  "Telmisartan 80mg",
  "Losartan 50mg",
  "Ramipril 5mg",
  "Enalapril 5mg",
  "Metoprolol 25mg",
  "Metoprolol 50mg",
  "Atenolol 50mg",
  "Bisoprolol 5mg",
  "Atorvastatin 10mg",
  "Atorvastatin 20mg",
  "Rosuvastatin 10mg",
  "Clopidogrel 75mg",
  // Thyroid
  "Levothyroxine 25mcg",
  "Levothyroxine 50mcg",
  "Levothyroxine 100mcg",
  // Urology / Gynae
  "Tamsulosin 0.4mg",
  "Finasteride 5mg",
  "Sildenafil 50mg",
  // CNS / Psych
  "Sertraline 50mg",
  "Escitalopram 10mg",
  "Alprazolam 0.25mg",
  "Clonazepam 0.5mg",
  "Gabapentin 300mg",
  "Pregabalin 75mg",
  "Amitriptyline 10mg",
  // Topicals
  "Clotrimazole cream 1%",
  "Terbinafine cream 1%",
  "Mupirocin ointment 2%",
  "Betamethasone cream 0.05%",
  "Calamine lotion",
  // Supplements / Misc
  "Vitamin D3 60,000 IU",
  "Vitamin B12 1500mcg",
  "Vitamin B complex",
  "Calcium + Vitamin D3",
  "Iron + Folic Acid",
  "Zinc 20mg",
  "Multivitamin tablet",
  "Probiotic sachet",
  "ORS sachet",
  "Diosmin + Hesperidin",
  "Lactulose syrup 15ml",
];

export const COMMON_DOSES = [
  "1 tablet",
  "2 tablets",
  "1/2 tablet",
  "5 ml",
  "10 ml",
  "1 capsule",
  "2 puffs",
  "1 sachet",
];

export const COMMON_FREQUENCIES = [
  "Once daily",
  "Twice daily",
  "3 times daily",
  "4 times daily",
  "Every 6 hours",
  "Every 8 hours",
  "Every 12 hours",
  "Before breakfast",
  "At bedtime",
  "SOS (as needed)",
];

export const COMMON_DURATIONS = [
  "3 days",
  "5 days",
  "7 days",
  "10 days",
  "14 days",
  "1 month",
  "3 months",
  "Continue",
];

export const COMMON_INSTRUCTIONS = [
  "After meals",
  "Before meals",
  "With water",
  "With milk",
  "Empty stomach",
  "At bedtime",
  "Avoid alcohol",
  "Complete the course",
];

export const COMMON_TESTS = [
  "CBC",
  "ESR",
  "CRP",
  "Blood sugar (fasting)",
  "Blood sugar (postprandial)",
  "HbA1c",
  "Lipid profile",
  "LFT",
  "KFT",
  "Thyroid profile",
  "Urine routine",
  "Chest X-Ray",
  "ECG",
  "USG abdomen",
  "COVID RT-PCR",
  "Dengue NS1",
  "Widal test",
];
