// Curated suggestion lists powering autocomplete (datalists) and quick-add
// chips inside the doctor prescription form. These are intentionally generic
// and not exhaustive — they're meant to speed up the most common entries.
// Doctors can always type anything; the lists only guide, never restrict.
//
// Lists are deliberately broad: ~250 symptoms, ~250 diagnoses, ~300 medicine
// strength variants. Datalist + chip pickers are designed to filter as the
// doctor types so a long list doesn't slow them down.

export const COMMON_SYMPTOMS = [
  // ─── General / Constitutional ────────────────────────────────────
  "Fever",
  "High-grade fever",
  "Low-grade fever",
  "Continuous fever",
  "Intermittent fever",
  "Chills",
  "Sweating",
  "Night sweats",
  "Rigors",
  "Fatigue",
  "Weakness",
  "Lethargy",
  "Malaise",
  "Loss of appetite",
  "Weight loss",
  "Weight gain",
  "Dehydration",
  "Excessive thirst",
  "Excessive hunger",
  "Generalized body ache",
  // ─── Head / ENT ──────────────────────────────────────────────────
  "Headache",
  "Migraine",
  "Tension headache",
  "Cluster headache",
  "Sinus pain",
  "Facial pain",
  "Sore throat",
  "Hoarseness",
  "Loss of voice",
  "Difficulty swallowing",
  "Painful swallowing",
  "Runny nose",
  "Nasal congestion",
  "Sneezing",
  "Post-nasal drip",
  "Nosebleed",
  "Loss of smell",
  "Loss of taste",
  "Toothache",
  "Bleeding gums",
  "Mouth ulcers",
  "Dry mouth",
  "Bad breath",
  "Tongue swelling",
  "Jaw pain",
  // ─── Ear ──────────────────────────────────────────────────────────
  "Ear pain",
  "Ear discharge",
  "Hearing loss",
  "Ringing in ears",
  "Ear blockage",
  "Itchy ears",
  // ─── Eye ──────────────────────────────────────────────────────────
  "Eye redness",
  "Eye pain",
  "Eye discharge",
  "Blurred vision",
  "Double vision",
  "Photophobia",
  "Watery eyes",
  "Dry eyes",
  "Itchy eyes",
  "Sudden vision loss",
  "Flashes / floaters",
  // ─── Respiratory ─────────────────────────────────────────────────
  "Cough",
  "Dry cough",
  "Productive cough",
  "Cough with blood",
  "Persistent cough",
  "Whooping cough",
  "Shortness of breath",
  "Wheezing",
  "Chest tightness",
  "Rapid breathing",
  "Difficulty breathing on exertion",
  "Difficulty breathing lying down",
  "Snoring",
  "Sleep apnoea",
  // ─── Cardiovascular ──────────────────────────────────────────────
  "Chest pain",
  "Pressure-like chest pain",
  "Burning chest pain",
  "Palpitations",
  "Skipped heartbeats",
  "Rapid heartbeat",
  "Slow heartbeat",
  "Swollen ankles",
  "Pedal oedema",
  "Fainting",
  "Pre-syncope / dizziness on standing",
  "Cyanosis",
  "Cold extremities",
  "Calf pain on walking",
  // ─── Gastrointestinal ────────────────────────────────────────────
  "Nausea",
  "Vomiting",
  "Vomiting with blood",
  "Projectile vomiting",
  "Abdominal pain",
  "Epigastric pain",
  "Right upper quadrant pain",
  "Right lower quadrant pain",
  "Left upper quadrant pain",
  "Left lower quadrant pain",
  "Generalized abdominal pain",
  "Abdominal bloating",
  "Abdominal distension",
  "Heartburn",
  "Acid reflux",
  "Indigestion",
  "Diarrhea",
  "Loose stools",
  "Bloody stools",
  "Black tarry stools",
  "Mucus in stools",
  "Constipation",
  "Painful defecation",
  "Anal pain",
  "Anal bleeding",
  "Jaundice",
  "Pale stools",
  "Dark urine",
  // ─── Genitourinary ───────────────────────────────────────────────
  "Burning urination",
  "Frequent urination",
  "Urgency to urinate",
  "Blood in urine",
  "Difficulty urinating",
  "Inability to urinate",
  "Cloudy urine",
  "Foul-smelling urine",
  "Decreased urine output",
  "Increased urine output (polyuria)",
  "Flank pain",
  "Loin pain",
  "Genital itching",
  "Genital discharge",
  "Genital ulcer",
  "Painful intercourse",
  "Erectile dysfunction",
  "Premature ejaculation",
  "Loss of libido",
  // ─── Gynaecological / Obstetric ──────────────────────────────────
  "Irregular periods",
  "Heavy menstrual bleeding",
  "Light menstrual bleeding",
  "Painful periods",
  "Missed period",
  "Bleeding between periods",
  "Postmenopausal bleeding",
  "Vaginal discharge",
  "Vaginal itching",
  "Pelvic pain",
  "Breast pain",
  "Breast lump",
  "Nipple discharge",
  "Hot flashes",
  "Pregnancy nausea",
  "Decreased fetal movements",
  // ─── Musculoskeletal ─────────────────────────────────────────────
  "Joint pain",
  "Joint swelling",
  "Joint stiffness",
  "Morning stiffness",
  "Back pain",
  "Lower back pain",
  "Neck pain",
  "Shoulder pain",
  "Knee pain",
  "Hip pain",
  "Ankle pain",
  "Wrist pain",
  "Muscle pain",
  "Muscle cramps",
  "Muscle weakness",
  "Limb swelling",
  "Limited range of motion",
  "Sprain",
  "Strain",
  // ─── Neurological ────────────────────────────────────────────────
  "Dizziness",
  "Vertigo",
  "Imbalance",
  "Difficulty walking",
  "Loss of consciousness",
  "Seizure",
  "Tremor",
  "Numbness",
  "Tingling sensation",
  "Pins and needles",
  "Slurred speech",
  "Memory problems",
  "Confusion",
  "Disorientation",
  "Difficulty concentrating",
  "Sudden weakness one side",
  "Facial drooping",
  "Difficulty speaking",
  "Visual field loss",
  // ─── Skin / Dermatological ───────────────────────────────────────
  "Rash",
  "Itching",
  "Hives",
  "Skin redness",
  "Skin peeling",
  "Skin discoloration",
  "Skin lump",
  "Mole change",
  "Wound not healing",
  "Easy bruising",
  "Hair loss",
  "Excessive hair growth",
  "Dandruff",
  "Dry skin",
  "Excessive sweating",
  "Acne",
  "Boil",
  "Skin abscess",
  "Insect bite reaction",
  // ─── Endocrine / Metabolic ───────────────────────────────────────
  "Heat intolerance",
  "Cold intolerance",
  "Tremors of hand",
  "Palpitations on exertion",
  "Slow growth",
  "Delayed puberty",
  // ─── Psychiatric / Sleep ─────────────────────────────────────────
  "Insomnia",
  "Excessive sleep",
  "Daytime sleepiness",
  "Anxiety",
  "Panic attacks",
  "Depression",
  "Low mood",
  "Mood swings",
  "Suicidal thoughts",
  "Hallucinations",
  "Memory loss",
  "Poor concentration",
  // ─── Lymphatic / Haematological ──────────────────────────────────
  "Swollen lymph nodes",
  "Easy bleeding",
  "Pallor",
  "Recurrent infections",
  // ─── Paediatric specific ─────────────────────────────────────────
  "Excessive crying in infant",
  "Refusing feeds",
  "Decreased activity in child",
  "Diaper rash",
  "Failure to thrive",
];

export const COMMON_DIAGNOSES = [
  // ─── Respiratory ─────────────────────────────────────────────────
  "Upper respiratory tract infection",
  "Lower respiratory tract infection",
  "Acute pharyngitis",
  "Acute tonsillitis",
  "Acute laryngitis",
  "Acute sinusitis",
  "Chronic sinusitis",
  "Allergic rhinitis",
  "Acute bronchitis",
  "Chronic bronchitis",
  "Bronchiolitis",
  "Pneumonia",
  "Community-acquired pneumonia",
  "Aspiration pneumonia",
  "Asthma",
  "Asthma exacerbation",
  "COPD",
  "COPD exacerbation",
  "Tuberculosis (suspected)",
  "Allergic cough",
  "Pertussis (suspected)",
  // ─── Viral / Tropical ────────────────────────────────────────────
  "Viral fever",
  "Influenza",
  "COVID-19",
  "Dengue fever",
  "Typhoid fever",
  "Malaria",
  "Chikungunya",
  "Viral hepatitis",
  "Hepatitis A",
  "Hepatitis B",
  "Hepatitis C",
  "Chickenpox",
  "Measles",
  "Mumps",
  "Rubella",
  "Hand-foot-and-mouth disease",
  "Herpes simplex",
  "Herpes zoster (Shingles)",
  // ─── GI ──────────────────────────────────────────────────────────
  "Acute gastroenteritis",
  "Food poisoning",
  "Gastritis",
  "GERD (Acid reflux)",
  "Peptic ulcer disease",
  "Functional dyspepsia",
  "Irritable bowel syndrome",
  "Inflammatory bowel disease",
  "Constipation",
  "Diarrhea (acute)",
  "Diarrhea (chronic)",
  "Lactose intolerance",
  "Hemorrhoids",
  "Anal fissure",
  "Cholelithiasis (Gallstones)",
  "Acute cholecystitis",
  "Pancreatitis",
  "Acute appendicitis (suspected)",
  // ─── Genitourinary ───────────────────────────────────────────────
  "Urinary tract infection",
  "Pyelonephritis",
  "Cystitis",
  "Urethritis",
  "Kidney stones",
  "Acute kidney injury",
  "Chronic kidney disease",
  "Prostatitis",
  "Benign prostatic hyperplasia",
  "Erectile dysfunction",
  "Premature ejaculation",
  // ─── Gynae / Obstetric ───────────────────────────────────────────
  "Menstrual irregularity",
  "Dysmenorrhea",
  "Menorrhagia",
  "Premenstrual syndrome",
  "PCOS",
  "Vaginal candidiasis",
  "Bacterial vaginosis",
  "Trichomoniasis",
  "Pelvic inflammatory disease",
  "Uterine fibroids",
  "Endometriosis",
  "Menopausal syndrome",
  "Pregnancy (uncomplicated)",
  "Hyperemesis gravidarum",
  "Gestational diabetes",
  "Preeclampsia",
  "Mastitis",
  // ─── Cardiac ─────────────────────────────────────────────────────
  "Hypertension",
  "Stage 1 hypertension",
  "Stage 2 hypertension",
  "Hypertensive urgency",
  "Coronary artery disease",
  "Angina pectoris",
  "Acute coronary syndrome (suspected)",
  "Heart failure",
  "Atrial fibrillation",
  "Supraventricular tachycardia",
  "Bradycardia",
  "Postural hypotension",
  "Deep vein thrombosis (suspected)",
  "Varicose veins",
  // ─── Endocrine / Metabolic ───────────────────────────────────────
  "Type 2 diabetes mellitus",
  "Type 1 diabetes mellitus",
  "Pre-diabetes",
  "Diabetic ketoacidosis",
  "Hypoglycemia",
  "Hyperlipidemia",
  "Mixed dyslipidemia",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Subclinical hypothyroidism",
  "Goitre",
  "Obesity",
  "Metabolic syndrome",
  "Vitamin D deficiency",
  "Vitamin B12 deficiency",
  "Iron deficiency anaemia",
  "Anaemia of chronic disease",
  "Hyperuricemia",
  "Gout",
  // ─── Neuro ───────────────────────────────────────────────────────
  "Migraine",
  "Migraine with aura",
  "Tension headache",
  "Cluster headache",
  "Vertigo (BPPV)",
  "Meniere's disease",
  "Vestibular neuritis",
  "Stroke (suspected)",
  "Transient ischemic attack",
  "Bell's palsy",
  "Trigeminal neuralgia",
  "Carpal tunnel syndrome",
  "Sciatica",
  "Peripheral neuropathy",
  "Diabetic neuropathy",
  "Seizure disorder",
  "Parkinson's disease",
  "Dementia",
  // ─── ENT / Eye ───────────────────────────────────────────────────
  "Acute otitis media",
  "Otitis externa",
  "Otomycosis",
  "Wax impaction",
  "Conjunctivitis",
  "Bacterial conjunctivitis",
  "Viral conjunctivitis",
  "Allergic conjunctivitis",
  "Stye",
  "Chalazion",
  "Dry eye syndrome",
  "Refractive error",
  // ─── Skin ────────────────────────────────────────────────────────
  "Atopic dermatitis (Eczema)",
  "Contact dermatitis",
  "Seborrheic dermatitis",
  "Psoriasis",
  "Acne vulgaris",
  "Rosacea",
  "Urticaria (Hives)",
  "Tinea corporis",
  "Tinea cruris",
  "Tinea pedis",
  "Tinea capitis",
  "Onychomycosis",
  "Scabies",
  "Pediculosis (Lice)",
  "Cellulitis",
  "Impetigo",
  "Folliculitis",
  "Furuncle / Boil",
  "Vitiligo",
  "Melasma",
  "Wound infection",
  // ─── Musculoskeletal / Rheum ─────────────────────────────────────
  "Lower back pain",
  "Cervical spondylosis",
  "Lumbar spondylosis",
  "Frozen shoulder",
  "Osteoarthritis (knee)",
  "Osteoarthritis (hip)",
  "Rheumatoid arthritis",
  "Ankylosing spondylitis",
  "Plantar fasciitis",
  "Tennis elbow",
  "Golfer's elbow",
  "De Quervain's tenosynovitis",
  "Musculoskeletal strain",
  "Sprain (ankle)",
  "Sprain (wrist)",
  "Soft tissue injury",
  "Fibromyalgia",
  "Osteoporosis",
  // ─── Mental health ───────────────────────────────────────────────
  "Anxiety disorder",
  "Generalized anxiety disorder",
  "Panic disorder",
  "Depression",
  "Major depressive episode",
  "Bipolar disorder",
  "Insomnia",
  "Adjustment disorder",
  "PTSD",
  "OCD",
  "ADHD",
  "Substance use disorder",
  // ─── Allergic / Immune ───────────────────────────────────────────
  "Drug allergy",
  "Food allergy",
  "Anaphylaxis (treated)",
  // ─── Paediatrics ─────────────────────────────────────────────────
  "Croup",
  "Acute otitis media (paediatric)",
  "Worm infestation",
  "Threadworm infestation",
  "Diaper dermatitis",
  "Failure to thrive",
  "Febrile seizure",
  // ─── Misc ────────────────────────────────────────────────────────
  "Dental caries",
  "Apthous ulcer",
  "Heat exhaustion",
  "Hangover",
  "Motion sickness",
  "Insect bite",
  "Animal bite (post-exposure)",
];

// Common medicines used across general practice. Format includes strength
// so the doctor can pick a prefilled entry and tweak as needed. Includes
// generic name primary; brand names accessible via medicines-catalog
// lookup so the same Rx string matches inventory whichever the doctor
// types.
export const COMMON_MEDICINES = [
  // ─── Analgesics / Antipyretics ───────────────────────────────────
  "Paracetamol 500mg",
  "Paracetamol 650mg",
  "Paracetamol 1000mg",
  "Paracetamol syrup 250mg/5ml",
  "Paracetamol drops 100mg/ml",
  "Ibuprofen 200mg",
  "Ibuprofen 400mg",
  "Ibuprofen 600mg",
  "Ibuprofen syrup 100mg/5ml",
  "Diclofenac 50mg",
  "Diclofenac 75mg SR",
  "Diclofenac gel 1%",
  "Naproxen 250mg",
  "Naproxen 500mg",
  "Aceclofenac 100mg",
  "Aceclofenac + Paracetamol",
  "Etoricoxib 60mg",
  "Etoricoxib 90mg",
  "Mefenamic acid 250mg",
  "Mefenamic acid 500mg",
  "Aspirin 75mg",
  "Aspirin 150mg",
  "Aspirin 325mg",
  "Tramadol 50mg",
  "Tramadol 100mg SR",
  "Tramadol + Paracetamol",
  // ─── Antibiotics — Penicillins ──────────────────────────────────
  "Amoxicillin 250mg",
  "Amoxicillin 500mg",
  "Amoxicillin syrup 125mg/5ml",
  "Amoxicillin syrup 250mg/5ml",
  "Amoxicillin + Clavulanic Acid 375mg",
  "Amoxicillin + Clavulanic Acid 625mg",
  "Amoxicillin + Clavulanic Acid 1g",
  "Amoxicillin + Clavulanic Acid syrup 228mg/5ml",
  "Ampicillin 500mg",
  "Cloxacillin 500mg",
  // ─── Antibiotics — Cephalosporins ───────────────────────────────
  "Cephalexin 250mg",
  "Cephalexin 500mg",
  "Cefadroxil 500mg",
  "Cefuroxime 250mg",
  "Cefuroxime 500mg",
  "Cefixime 200mg",
  "Cefixime 400mg",
  "Cefixime + Ofloxacin",
  "Cefpodoxime 200mg",
  "Cefpodoxime + Clavulanic Acid",
  "Ceftriaxone 1g injection",
  "Cefoperazone + Sulbactam injection",
  // ─── Antibiotics — Macrolides / Tetracyclines ───────────────────
  "Azithromycin 250mg",
  "Azithromycin 500mg",
  "Azithromycin syrup 200mg/5ml",
  "Clarithromycin 250mg",
  "Clarithromycin 500mg",
  "Erythromycin 250mg",
  "Erythromycin 500mg",
  "Doxycycline 100mg",
  "Minocycline 100mg",
  // ─── Antibiotics — Quinolones / Misc ────────────────────────────
  "Ciprofloxacin 250mg",
  "Ciprofloxacin 500mg",
  "Levofloxacin 250mg",
  "Levofloxacin 500mg",
  "Levofloxacin 750mg",
  "Ofloxacin 200mg",
  "Ofloxacin 400mg",
  "Ofloxacin + Ornidazole",
  "Norfloxacin 400mg",
  "Norfloxacin + Tinidazole",
  "Metronidazole 200mg",
  "Metronidazole 400mg",
  "Metronidazole 500mg IV",
  "Tinidazole 500mg",
  "Tinidazole 1g",
  "Nitrofurantoin 100mg",
  "Trimethoprim + Sulfamethoxazole 480mg",
  "Trimethoprim + Sulfamethoxazole 960mg",
  "Linezolid 600mg",
  "Vancomycin 500mg injection",
  // ─── Antifungals ─────────────────────────────────────────────────
  "Fluconazole 50mg",
  "Fluconazole 150mg",
  "Fluconazole 200mg",
  "Itraconazole 100mg",
  "Itraconazole 200mg",
  "Terbinafine 250mg",
  "Terbinafine cream 1%",
  "Ketoconazole 200mg",
  "Ketoconazole shampoo 2%",
  "Griseofulvin 250mg",
  "Clotrimazole cream 1%",
  "Clotrimazole pessary 100mg",
  "Miconazole gel 2%",
  "Nystatin oral suspension",
  // ─── Antivirals / Antiparasitics ─────────────────────────────────
  "Acyclovir 200mg",
  "Acyclovir 400mg",
  "Acyclovir 800mg",
  "Acyclovir cream 5%",
  "Valacyclovir 500mg",
  "Valacyclovir 1g",
  "Oseltamivir 30mg",
  "Oseltamivir 75mg",
  "Albendazole 400mg",
  "Mebendazole 100mg",
  "Ivermectin 6mg",
  "Ivermectin 12mg",
  "Praziquantel 600mg",
  "Hydroxychloroquine 200mg",
  "Hydroxychloroquine 400mg",
  "Artemether + Lumefantrine 80/480",
  "Chloroquine 250mg",
  "Primaquine 7.5mg",
  // ─── GI / Acid suppression ───────────────────────────────────────
  "Omeprazole 20mg",
  "Omeprazole 40mg",
  "Pantoprazole 20mg",
  "Pantoprazole 40mg",
  "Pantoprazole IV 40mg",
  "Esomeprazole 20mg",
  "Esomeprazole 40mg",
  "Rabeprazole 10mg",
  "Rabeprazole 20mg",
  "Rabeprazole + Domperidone",
  "Lansoprazole 30mg",
  "Ranitidine 150mg",
  "Famotidine 20mg",
  "Famotidine 40mg",
  "Sucralfate 1g",
  "Sucralfate suspension 1g/10ml",
  "Antacid syrup 10ml",
  "Magaldrate suspension",
  "Bismuth subsalicylate",
  // ─── Antiemetics / Prokinetics ───────────────────────────────────
  "Ondansetron 4mg",
  "Ondansetron 8mg",
  "Ondansetron syrup 2mg/5ml",
  "Domperidone 10mg",
  "Domperidone syrup",
  "Metoclopramide 10mg",
  "Promethazine 25mg",
  "Doxylamine + Pyridoxine",
  "Cyclizine 50mg",
  // ─── Laxatives / Antidiarrhoeals ────────────────────────────────
  "Lactulose syrup 15ml",
  "Lactulose syrup 10ml",
  "Bisacodyl 5mg",
  "Senna 8.6mg",
  "Polyethylene glycol sachet",
  "Loperamide 2mg",
  "Diphenoxylate + Atropine",
  "Racecadotril 100mg",
  "ORS sachet",
  "Probiotic sachet",
  "Saccharomyces boulardii sachet",
  // ─── Antihistamines ─────────────────────────────────────────────
  "Loratadine 10mg",
  "Loratadine syrup",
  "Cetirizine 10mg",
  "Cetirizine syrup 5mg/5ml",
  "Levocetirizine 5mg",
  "Levocetirizine syrup 2.5mg/5ml",
  "Fexofenadine 120mg",
  "Fexofenadine 180mg",
  "Bilastine 20mg",
  "Desloratadine 5mg",
  "Chlorpheniramine 4mg",
  "Hydroxyzine 10mg",
  "Hydroxyzine 25mg",
  "Diphenhydramine 25mg",
  "Diphenhydramine 50mg",
  // ─── Respiratory ─────────────────────────────────────────────────
  "Montelukast 4mg",
  "Montelukast 5mg",
  "Montelukast 10mg",
  "Montelukast + Levocetirizine",
  "Salbutamol inhaler 100mcg",
  "Salbutamol nebulizer solution",
  "Salbutamol syrup 2mg/5ml",
  "Levosalbutamol inhaler 50mcg",
  "Budesonide inhaler 100mcg",
  "Budesonide inhaler 200mcg",
  "Budesonide nebulizer 0.5mg",
  "Fluticasone inhaler 125mcg",
  "Fluticasone nasal spray",
  "Salbutamol + Ipratropium nebulizer",
  "Formoterol + Budesonide inhaler",
  "Salmeterol + Fluticasone inhaler",
  "Tiotropium 18mcg",
  "Theophylline 200mg SR",
  "Doxofylline 400mg",
  "Ambroxol syrup 30mg/5ml",
  "Ambroxol 30mg tablet",
  "Bromhexine 8mg",
  "Acetylcysteine 600mg",
  "Dextromethorphan syrup",
  "Codeine + Chlorpheniramine syrup",
  "Levodropropizine syrup",
  "Guaifenesin syrup",
  // ─── Steroids ────────────────────────────────────────────────────
  "Prednisolone 5mg",
  "Prednisolone 10mg",
  "Prednisolone 20mg",
  "Methylprednisolone 4mg",
  "Methylprednisolone 16mg",
  "Dexamethasone 0.5mg",
  "Dexamethasone 4mg",
  "Dexamethasone IV 8mg",
  "Hydrocortisone cream 1%",
  "Triamcinolone oral paste 0.1%",
  // ─── Diabetes ────────────────────────────────────────────────────
  "Metformin 500mg",
  "Metformin 850mg",
  "Metformin 1000mg",
  "Metformin SR 500mg",
  "Metformin SR 1000mg",
  "Glimepiride 1mg",
  "Glimepiride 2mg",
  "Glimepiride 4mg",
  "Glipizide 5mg",
  "Glipizide 10mg",
  "Gliclazide 80mg",
  "Gliclazide MR 60mg",
  "Sitagliptin 50mg",
  "Sitagliptin 100mg",
  "Sitagliptin + Metformin",
  "Vildagliptin 50mg",
  "Linagliptin 5mg",
  "Teneligliptin 20mg",
  "Empagliflozin 10mg",
  "Empagliflozin 25mg",
  "Dapagliflozin 5mg",
  "Dapagliflozin 10mg",
  "Pioglitazone 15mg",
  "Pioglitazone 30mg",
  "Acarbose 50mg",
  "Voglibose 0.2mg",
  "Voglibose 0.3mg",
  "Insulin glargine",
  "Insulin lispro",
  "Insulin aspart",
  "Insulin regular",
  "Premixed insulin 30/70",
  // ─── Cardiovascular ──────────────────────────────────────────────
  "Amlodipine 2.5mg",
  "Amlodipine 5mg",
  "Amlodipine 10mg",
  "Nifedipine SR 30mg",
  "Cilnidipine 10mg",
  "Telmisartan 20mg",
  "Telmisartan 40mg",
  "Telmisartan 80mg",
  "Telmisartan + Amlodipine",
  "Telmisartan + Hydrochlorothiazide",
  "Losartan 25mg",
  "Losartan 50mg",
  "Losartan 100mg",
  "Olmesartan 20mg",
  "Olmesartan 40mg",
  "Valsartan 80mg",
  "Ramipril 2.5mg",
  "Ramipril 5mg",
  "Ramipril 10mg",
  "Enalapril 2.5mg",
  "Enalapril 5mg",
  "Lisinopril 5mg",
  "Lisinopril 10mg",
  "Metoprolol 25mg",
  "Metoprolol 50mg",
  "Metoprolol 100mg",
  "Metoprolol XL 25mg",
  "Atenolol 25mg",
  "Atenolol 50mg",
  "Bisoprolol 2.5mg",
  "Bisoprolol 5mg",
  "Carvedilol 6.25mg",
  "Carvedilol 12.5mg",
  "Nebivolol 5mg",
  "Atorvastatin 10mg",
  "Atorvastatin 20mg",
  "Atorvastatin 40mg",
  "Atorvastatin 80mg",
  "Rosuvastatin 5mg",
  "Rosuvastatin 10mg",
  "Rosuvastatin 20mg",
  "Simvastatin 20mg",
  "Ezetimibe 10mg",
  "Fenofibrate 145mg",
  "Fenofibrate 160mg",
  "Clopidogrel 75mg",
  "Clopidogrel + Aspirin",
  "Ticagrelor 90mg",
  "Prasugrel 10mg",
  "Warfarin 1mg",
  "Warfarin 2mg",
  "Warfarin 5mg",
  "Apixaban 2.5mg",
  "Apixaban 5mg",
  "Rivaroxaban 10mg",
  "Rivaroxaban 20mg",
  "Dabigatran 110mg",
  "Furosemide 20mg",
  "Furosemide 40mg",
  "Torsemide 10mg",
  "Spironolactone 25mg",
  "Spironolactone 50mg",
  "Hydrochlorothiazide 12.5mg",
  "Hydrochlorothiazide 25mg",
  "Indapamide 1.5mg SR",
  "Digoxin 0.25mg",
  "Isosorbide mononitrate 20mg",
  "Isosorbide dinitrate 5mg sublingual",
  "Nitroglycerin spray",
  // ─── Thyroid / Endocrine ─────────────────────────────────────────
  "Levothyroxine 12.5mcg",
  "Levothyroxine 25mcg",
  "Levothyroxine 50mcg",
  "Levothyroxine 75mcg",
  "Levothyroxine 100mcg",
  "Levothyroxine 125mcg",
  "Levothyroxine 150mcg",
  "Carbimazole 5mg",
  "Carbimazole 10mg",
  "Methimazole 5mg",
  "Propylthiouracil 50mg",
  // ─── Urology / Gynae ─────────────────────────────────────────────
  "Tamsulosin 0.4mg",
  "Tamsulosin + Dutasteride",
  "Finasteride 1mg",
  "Finasteride 5mg",
  "Dutasteride 0.5mg",
  "Sildenafil 25mg",
  "Sildenafil 50mg",
  "Sildenafil 100mg",
  "Tadalafil 5mg",
  "Tadalafil 20mg",
  "Vardenafil 20mg",
  "Solifenacin 5mg",
  "Solifenacin 10mg",
  "Mirabegron 25mg",
  "Mirabegron 50mg",
  "Estradiol 1mg",
  "Conjugated estrogens 0.625mg",
  "Norethindrone 5mg",
  "Medroxyprogesterone 10mg",
  "Combined oral contraceptive pill",
  "Progestin-only pill",
  "Tranexamic acid 500mg",
  "Mefenamic acid for menorrhagia 500mg",
  "Folic acid 5mg",
  "Folic acid + Iron",
  "Calcium + Vitamin D3",
  "Iron + Folic Acid",
  "Methylergometrine 0.125mg",
  "Misoprostol 200mcg",
  // ─── CNS / Psych / Pain ─────────────────────────────────────────
  "Sertraline 25mg",
  "Sertraline 50mg",
  "Sertraline 100mg",
  "Escitalopram 5mg",
  "Escitalopram 10mg",
  "Escitalopram 20mg",
  "Fluoxetine 20mg",
  "Citalopram 20mg",
  "Paroxetine 20mg",
  "Venlafaxine 75mg SR",
  "Venlafaxine 150mg SR",
  "Duloxetine 30mg",
  "Duloxetine 60mg",
  "Mirtazapine 15mg",
  "Mirtazapine 30mg",
  "Bupropion SR 150mg",
  "Alprazolam 0.25mg",
  "Alprazolam 0.5mg",
  "Clonazepam 0.25mg",
  "Clonazepam 0.5mg",
  "Diazepam 5mg",
  "Lorazepam 1mg",
  "Lorazepam 2mg",
  "Etizolam 0.25mg",
  "Etizolam 0.5mg",
  "Quetiapine 25mg",
  "Quetiapine 100mg",
  "Olanzapine 5mg",
  "Olanzapine 10mg",
  "Risperidone 1mg",
  "Risperidone 2mg",
  "Aripiprazole 10mg",
  "Haloperidol 5mg",
  "Lithium 300mg",
  "Sodium valproate 200mg",
  "Sodium valproate 500mg",
  "Lamotrigine 25mg",
  "Lamotrigine 100mg",
  "Levetiracetam 250mg",
  "Levetiracetam 500mg",
  "Levetiracetam 1000mg",
  "Carbamazepine 200mg",
  "Phenytoin 100mg",
  "Topiramate 25mg",
  "Topiramate 50mg",
  "Gabapentin 100mg",
  "Gabapentin 300mg",
  "Gabapentin 400mg",
  "Pregabalin 75mg",
  "Pregabalin 150mg",
  "Amitriptyline 10mg",
  "Amitriptyline 25mg",
  "Nortriptyline 10mg",
  "Donepezil 5mg",
  "Donepezil 10mg",
  "Memantine 5mg",
  "Memantine 10mg",
  "Methylphenidate 10mg",
  "Atomoxetine 18mg",
  "Atomoxetine 40mg",
  // ─── Topicals / Dermatological ──────────────────────────────────
  "Clotrimazole cream 1%",
  "Terbinafine cream 1%",
  "Ketoconazole cream 2%",
  "Miconazole cream 2%",
  "Mupirocin ointment 2%",
  "Fusidic acid cream 2%",
  "Silver sulfadiazine cream 1%",
  "Betamethasone cream 0.05%",
  "Betamethasone + Neomycin + Clotrimazole",
  "Mometasone cream 0.1%",
  "Hydrocortisone cream 1%",
  "Tacrolimus ointment 0.03%",
  "Tacrolimus ointment 0.1%",
  "Calcipotriol ointment",
  "Permethrin cream 5%",
  "Benzoyl peroxide gel 2.5%",
  "Adapalene gel 0.1%",
  "Tretinoin cream 0.025%",
  "Clindamycin gel 1%",
  "Hydroquinone 2%",
  "Calamine lotion",
  "Salicylic acid 6%",
  "Coal tar shampoo",
  "Selenium sulfide shampoo",
  // ─── Ophthalmic / ENT drops ──────────────────────────────────────
  "Moxifloxacin eye drops 0.5%",
  "Tobramycin eye drops 0.3%",
  "Ciprofloxacin eye drops 0.3%",
  "Olopatadine eye drops 0.1%",
  "Sodium cromoglicate eye drops",
  "Carboxymethyl cellulose eye drops",
  "Timolol eye drops 0.5%",
  "Latanoprost eye drops",
  "Brimonidine eye drops",
  "Ofloxacin ear drops 0.3%",
  "Ciprofloxacin ear drops 0.3%",
  "Clotrimazole ear drops 1%",
  "Fluticasone nasal spray",
  "Mometasone nasal spray",
  "Xylometazoline nasal drops",
  "Saline nasal spray",
  // ─── Supplements ─────────────────────────────────────────────────
  "Vitamin D3 60,000 IU",
  "Vitamin D3 1000 IU",
  "Vitamin D3 2000 IU",
  "Vitamin B12 1500mcg",
  "Vitamin B12 500mcg",
  "Vitamin B complex",
  "Vitamin C 500mg",
  "Vitamin E 400 IU",
  "Calcium carbonate 500mg",
  "Calcium citrate 1000mg",
  "Magnesium 250mg",
  "Zinc 20mg",
  "Zinc + Vitamin C",
  "Multivitamin tablet",
  "Multivitamin syrup",
  "Omega-3 fish oil 1000mg",
  "Coenzyme Q10 100mg",
  "Iron sucrose injection",
  // ─── Misc ────────────────────────────────────────────────────────
  "Diosmin + Hesperidin",
  "Allopurinol 100mg",
  "Allopurinol 300mg",
  "Febuxostat 40mg",
  "Febuxostat 80mg",
  "Colchicine 0.5mg",
  "Methotrexate 7.5mg",
  "Methotrexate 15mg",
  "Sulfasalazine 500mg",
  "Hydroxychloroquine 200mg",
  "Tetanus toxoid injection",
  "Influenza vaccine",
  "Hepatitis B vaccine",
  "Tetanus immunoglobulin",
  "Anti-rabies vaccine",
  "Insulin pen needles",
  "Lactic acid + Urea moisturizer",
  "Urea cream 10%",
  "ORS-L for elderly",
];

export const COMMON_DOSES = [
  "1 tablet",
  "2 tablets",
  "1/2 tablet",
  "1 capsule",
  "2 capsules",
  "5 ml",
  "10 ml",
  "15 ml",
  "20 ml",
  "1 sachet",
  "1 puff",
  "2 puffs",
  "1 drop",
  "2 drops",
  "1 application",
  "1 unit",
  "10 units",
  "20 units",
];

export const COMMON_FREQUENCIES = [
  "Once daily",
  "Twice daily",
  "3 times daily",
  "4 times daily",
  "Every 4 hours",
  "Every 6 hours",
  "Every 8 hours",
  "Every 12 hours",
  "Every 24 hours",
  "Before breakfast",
  "After breakfast",
  "Before lunch",
  "After lunch",
  "Before dinner",
  "After dinner",
  "At bedtime",
  "Morning",
  "Night",
  "Alternate days",
  "Weekly once",
  "SOS (as needed)",
  "Stat (single dose)",
];

export const COMMON_DURATIONS = [
  "1 day",
  "2 days",
  "3 days",
  "5 days",
  "7 days",
  "10 days",
  "14 days",
  "21 days",
  "1 month",
  "2 months",
  "3 months",
  "6 months",
  "Continue",
  "Lifelong",
  "Until follow-up",
];

export const COMMON_INSTRUCTIONS = [
  "After meals",
  "Before meals",
  "With meals",
  "With water",
  "With milk",
  "Empty stomach",
  "At bedtime",
  "First thing in the morning",
  "Avoid alcohol",
  "Avoid driving",
  "Complete the course",
  "Take with food to avoid stomach upset",
  "Do not crush or chew",
  "Shake well before use",
  "Apply locally",
  "Apply thinly",
  "Inhale through mouth",
  "Rinse mouth after use",
  "Do not stop abruptly",
];

export const COMMON_TESTS = [
  // Hematology
  "CBC",
  "ESR",
  "CRP",
  "Peripheral smear",
  "Reticulocyte count",
  "PT/INR",
  "aPTT",
  // Biochemistry — sugar
  "Blood sugar (fasting)",
  "Blood sugar (postprandial)",
  "Random blood sugar",
  "HbA1c",
  "Insulin (fasting)",
  // Biochemistry — lipid / liver / kidney
  "Lipid profile",
  "LFT",
  "KFT / RFT",
  "Serum creatinine",
  "Serum urea",
  "Serum uric acid",
  "Serum bilirubin",
  "Serum electrolytes (Na/K/Cl)",
  // Biochemistry — endocrine / vitamin
  "Thyroid profile (TSH, T3, T4)",
  "Free T3 / Free T4",
  "Vitamin D 25-OH",
  "Vitamin B12",
  "Folate",
  "Ferritin",
  "Iron studies",
  // Cardiac
  "Troponin I",
  "CK-MB",
  "NT-proBNP",
  "Lp(a)",
  // Inflammatory / Autoimmune
  "ANA",
  "RA factor",
  "Anti-CCP",
  // Urine
  "Urine routine",
  "Urine culture",
  "Urine microalbumin",
  "Urine pregnancy test",
  // Stool
  "Stool routine",
  "Stool culture",
  "Stool occult blood",
  // Imaging
  "Chest X-Ray PA view",
  "X-Ray (other)",
  "ECG",
  "2D Echo",
  "USG abdomen",
  "USG pelvis",
  "USG transvaginal",
  "CT scan brain",
  "CT scan chest",
  "CT scan abdomen",
  "MRI brain",
  "MRI spine",
  "Mammography",
  // Microbiology / Infectious
  "COVID RT-PCR",
  "Rapid antigen test (COVID)",
  "Dengue NS1",
  "Dengue IgM/IgG",
  "Malaria parasite (smear)",
  "Widal test",
  "Typhi-dot",
  "HIV (rapid)",
  "HBsAg",
  "Anti-HCV",
  "Mantoux test",
  "Sputum AFB",
  "Throat swab culture",
  // Pulmonary
  "PFT / Spirometry",
  "Peak flow",
  // GI / Endoscopy
  "UGI endoscopy",
  "Colonoscopy",
  "Liver elastography",
  // Misc
  "Bone densitometry (DEXA)",
  "Pap smear",
  "PSA",
  "Beta-hCG (qualitative)",
  "Beta-hCG (quantitative)",
  "Allergy panel",
];
