// POST /api/ai/scribe
//
// Receives a multipart/form-data with field `audio` (the consultation
// recording) and returns a structured SOAP note generated by Gemini.
//
// Hard cap on file size — a 30-min consultation in WebM/Opus 32kbps mono
// is ~7 MB. We allow up to 25 MB which covers an hour with headroom.
// Anything larger should be split client-side.

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { transcribeToSoap } from "@/lib/ai-scribe";
import { enforceRateLimit } from "@/lib/rate-limit-helpers";
import { log } from "@/lib/log";

export const runtime = "nodejs";
export const maxDuration = 120; // Vercel — Gemini audio can take a while

const MAX_BYTES = 25 * 1024 * 1024; // 25 MB

function isClinician(role: string | undefined): boolean {
  return role === "doctor" || role === "admin" || role === "nurse";
}

export async function POST(req: NextRequest) {
  // Rate limit is strict — each call is expensive (~$0.05 of Gemini
  // compute for a 15-min consultation).
  const blocked = await enforceRateLimit(req, "ai-scribe", 20, "10 m");
  if (blocked) return blocked;

  const session = await getServerSession(authOptions);
  const role = (session?.user as { role?: string } | undefined)?.role;
  if (!isClinician(role)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  let form: FormData;
  try {
    form = await req.formData();
  } catch {
    return NextResponse.json({ error: "Expected multipart/form-data" }, { status: 400 });
  }

  const audio = form.get("audio");
  if (!(audio instanceof Blob)) {
    return NextResponse.json({ error: "Missing 'audio' file in form" }, { status: 400 });
  }
  if (audio.size === 0) {
    return NextResponse.json({ error: "Audio file is empty" }, { status: 400 });
  }
  if (audio.size > MAX_BYTES) {
    return NextResponse.json(
      { error: `Audio too large (${Math.round(audio.size / 1024 / 1024)} MB). Split into smaller segments.` },
      { status: 413 }
    );
  }

  const buf = await audio.arrayBuffer();
  const mime = audio.type || "audio/webm";

  try {
    const soap = await transcribeToSoap({ audio: buf, mimeType: mime });
    return NextResponse.json({ soap });
  } catch (err) {
    log.error("ai_scribe.failed", err);
    const msg = err instanceof Error ? err.message : "Scribe failed";
    return NextResponse.json(
      {
        error: /GEMINI_API_KEY/.test(msg)
          ? "AI scribe is not configured."
          : "Could not transcribe audio. Try recording again with clearer speech.",
        detail: process.env.NODE_ENV === "development" ? msg : undefined,
      },
      { status: 502 }
    );
  }
}
